spring:
  #给项目来个名字
  application:
    name: lanlanim-transfer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 121.4.177.109
    port: 5672
    username: admin
    password: admin
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true


zk-config:
  zkAddress: 121.4.177.109:2181
  zkConnectTimeout: 15000
  zkTransfer: /transfer

app-config:
  nettyPort: 9001
